# Generated by Django 5.2.6 on 2025-09-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villain',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
