# Generated by Django 5.2.6 on 2025-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email_contato',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
